name: Deploy GRC Dashboard

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 89.116.191.136
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Executa o script de deploy criado no servidor
            /opt/dashboard-financeiro-grc/deploy.sh